---
title: Basic Malaria Model Report
output: html_document
params:
  birth_rate_human: NULL
  death_rate_human: NULL
  beta_human: NULL
  gamma_human: NULL
  birth_rate_mosquito: NULL
  death_rate_mosquito: NULL
  beta_mosquito: NULL
  susceptible_humans: NULL
  infectious_humans: NULL
  recovered_humans: NULL
  susceptible_mosquitoes: NULL
  infectious_mosquitoes: NULL
  model_output: NULL
---

```{r include=FALSE}
# load libraries
library(shiny)
library(bslib)
library(deSolve)
library(tidyverse)
library(plotly)
```


## Model results

```{r echo=FALSE}
ggplot(params$model_output, aes(x = time, y = population, color = compartment)) +
      geom_line() +
      theme_minimal() +
      scale_x_continuous(breaks = seq(2015, 2025, 2)) +
      labs(
        title = "Compartmental Model",
        color = "Compartment",
        x = "Time",
        y = "Population"
      )
```

## Model parameters

```{r echo=FALSE}
model_inputs <- tibble(
  input = c("birth_rate_human",
            "death_rate_human",
            "beta_human",
            "gamma_human",
            "birth_rate_mosquito",
            "death_rate_mosquito",
            "beta_mosquito",
            "susceptible_humans",
            "infectious_humans",
            "recovered_humans",
            "susceptible_mosquitoes",
            "infectious_mosquitoes"),
    values = c(params$birth_rate_human,
            params$death_rate_human,
            params$beta_human,
            params$gamma_human,
            params$birth_rate_mosquito,
            params$death_rate_mosquito,
            params$beta_mosquito,
            params$susceptible_humans,
            params$infectious_humans,
            params$recovered_humans,
            params$susceptible_mosquitoes,
            params$infectious_mosquitoes)
)

knitr::kable(model_inputs)
```

